<a href="https://colab.research.google.com/github/khamalismadie/Learn_TensorFlow/blob/main/Learn_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

TensorFlow Version

In [2]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.7.0


Load **Dataset**

In [3]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11501568/11490434 [==============================] - 0s 0us/step


Build a machine learning model

In [6]:
tf.keras.Sequential(
    layers=None, name=None
)

In [8]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [9]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.44631773,  0.12242728,  0.03123894,  0.6511169 , -0.20671321,
        -0.5897445 , -0.11625844,  0.06630038, -0.64613354,  0.762167  ]],
      dtype=float32)

In [10]:
tf.nn.softmax(predictions).numpy()

array([[0.13428918, 0.09713532, 0.08866956, 0.16481023, 0.06989294,
        0.04765241, 0.07650983, 0.09183359, 0.04503969, 0.18416733]],
      dtype=float32)

In [11]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [12]:
loss_fn(y_train[:1], predictions).numpy()

3.043822

In [13]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [14]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.2916 - accuracy: 0.9152
Epoch 2/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1426 - accuracy: 0.9578
Epoch 3/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.1051 - accuracy: 0.9677
Epoch 4/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.0877 - accuracy: 0.9730
Epoch 5/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0750 - accuracy: 0.9764


In [15]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [16]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.79054888e-07, 6.13513436e-08, 1.85594290e-05, 4.11772111e-04,
        2.42132226e-12, 1.65738788e-06, 1.73108042e-13, 9.99558151e-01,
        4.23970505e-06, 5.32723789e-06],
       [5.42289658e-10, 3.09795432e-05, 9.99942303e-01, 2.66521711e-05,
        3.16036955e-20, 8.84164297e-09, 1.02083708e-09, 5.90281816e-12,
        1.38380365e-08, 3.55897648e-16],
       [1.11954478e-06, 9.98381615e-01, 3.83456005e-04, 8.75565820e-06,
        2.42143487e-05, 5.62016885e-06, 4.79282517e-06, 1.00536877e-03,
        1.84373610e-04, 7.29027818e-07],
       [9.99750793e-01, 4.17670032e-09, 2.00944662e-04, 1.20575237e-06,
        1.37358906e-08, 1.84688076e-06, 5.47989293e-06, 3.07738046e-05,
        2.50748773e-08, 8.90401225e-06],
       [2.81523603e-06, 2.21055640e-09, 6.12187650e-05, 9.17563980e-08,
        9.82683837e-01, 5.51209587e-06, 4.37532708e-06, 1.66954938e-04,
        5.89401338e-07, 1.70745477e-02]], dtype=float32)>